main:
  - name: 关于我
    url: /authors/onceking
    weight: 1
  - name: 文章
    url: /posts/
    weight: 2
  - name: 日常
    url: /docs/
    weight: 3
  - name: 诗词
    url: /poet/
    weight: 4
  - name: 文章汇总
    url: /cat
    weight: 5
  - name: 文章统计
    url: /stats
    weight: 6